project_id = "gyczrmqalmwhrbbyfvli"

[functions.elevenlabs-conversation-token]
verify_jwt = false

[functions.clawdbot-chat]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.scan-business-card]
verify_jwt = false

[functions.elevenlabs-scribe-token]
verify_jwt = false